################### create vlans 10, 20 #######################

- name: configure vlan 10
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    - vlan_id: 10
    - vlan_name: management
    - state: present
  roles:
    - threefold.farm_mgmt.fsos_vlan

- name: configure vlan 20
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    - vlan_id: 20
    - vlan_name: business
    - state: present
  roles:
    - threefold.farm_mgmt.fsos_vlan


################### add access ports to vlans 10, 20 #######################

- name: add vlan 10 members
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    - interface_range: ethernet 1/1-3
    - mode: access
    - vlan_id: 10
  roles:
    - threefold.farm_mgmt.fsos_switchport

- name: add vlan 20 members
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    - interface_range: ethernet 1/4-6
    - mode: access
    - vlan_id: 20
  roles:
    - threefold.farm_mgmt.fsos_switchport


################### configure ip address for vlan interface 10 #######################

- name: configure ip address for vlan interface 10
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    - interface_name: vlan 10
    - ipv4: 10.10.10.10/24
  roles:
    - threefold.farm_mgmt.fsos_ip_address

################### configure lacp #######################

- name: configure lacp
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    - interface_range: ethernet 1/8-9
    - channel_group_id: 1
    - mode: auto
    - load_balance_option: src-ip
  roles:
    - threefold.farm_mgmt.fsos_lacp


################### bring up interface #######################

- name: configure ip address for vlan interface 10
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    - interface_range: ethernet 1/1-9
  roles:
    - threefold.farm_mgmt.fsos_interface_shutdown

################### configure port channel as trunk for vlans 10,20 #######################

- name: configure port channel as trunk for vlans 10,20
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
    - interface_range: port-channel 1
    - mode: trunk
    - vlan_id: 10,20
    - mode: trunk
  roles:
    - threefold.farm_mgmt.fsos_switchport


################### save config #######################

# - name: save running config to startup
#   hosts: all
#   connection: ansible.netcommon.network_cli
#   gather_facts: false
#   tasks:
#     - cisco.ios.ios_command:
#         commands:
#           - copy running-config startup-config
