---
- hosts: running
  gather_facts: no
  tasks:
    - name: power on
      community.general.ipmi_power:
        name: "{{ ansible_host }}"
        user: "{{ ipmi_user }}"
        password: "{{ ipmi_password }}"
        state: on


- hosts: stopped
  gather_facts: no
  tasks:
    - name: shutdown
      community.general.ipmi_power:
        name: "{{ ansible_host }}"
        user: "{{ ipmi_user }}"
        password: "{{ ipmi_password }}"
        state: off