- block:
  - name: configure lacp load balance
    cisco.ios.ios_command:
      commands:
        - configure terminal
        - "port-channel load-balance hash-field-select {{ load_balance_option }}"
  when: load_balance_option is defined

- name: configure port group members
  cisco.ios.ios_command:
    commands:
      - configure terminal
      - "interface {{ interface_range }}"
      - "channel-group {{ channel_group_id }} mode {{ mode }}"

