- block:
  - block:
    - name: ipv4 address config
      shell:
        cmd: net add interface {{ interface_name }} ip address {{ ip }}
    when: bond is not defined
  
  - block:
    - name: ipv4 address config
      shell:
        cmd: 
          net add bond {{ interface_name }} ip address {{ ip }}
    when: bond is defined
  
  when: ip is defined



- block:
  - block:
    - name: ipv6 address config
      shell:
        cmd: net add interface {{ interface_name }} ipv6 address {{ ipv6 }}
    when: bond is not defined
  
  - block:
    - name: ipv6 address config
      shell:
        cmd: 
          net add bond {{ interface_name }} ipv6 address {{ ipv6 }}
    when: bond is defined

  when: ipv6 is defined



- block:
  - name: commit changes
    shell: 
      cmd: net commit
  when: commit is defined
